name: Tweet

on:
  schedule:
    - cron: '*/3 * * * *' # Runs Bot every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Bot
        uses: dephraiim/twitter-bot-action@v1.2
        env:
          BOT_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          BOT_CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          BOT_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BOT_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
